In this tutorial, we want to solve the following example:

#Balanced Example

<img src="https://github.com/amirkfard/CVL609-W23/blob/main/img/mip_81.webp?raw=1\" width="700">
<img src="https://github.com/amirkfard/CVL609-W23/blob/main/img/mip_82.webp?raw=1\" width="700">
<img src="https://github.com/amirkfard/CVL609-W23/blob/main/img/mip_83.webp?raw=1\" width="700">
<img src="https://github.com/amirkfard/CVL609-W23/blob/main/img/mip_84.webp?raw=1\" width="700">

In [ ]:
import numpy as np
from scipy.optimize import linprog

# Define the coefficients for the objective function
#               WE WT WO ME MT MO HE HT HO
obj = np.array([5, 4, 3, 3, 2, 1, 9, 7, 5])


In [ ]:
#                WE WT WO ME MT MO HE HT HO               
lhs = np.array([[1, 1, 1, 0, 0, 0, 0, 0 ,0],
                [0, 0, 0, 1, 1, 1, 0, 0, 0],
                [0, 0, 0, 0, 0, 0, 1, 1, 1],
                [1, 0, 0, 1, 0, 0, 1, 0, 0],
                [0, 1, 0, 0, 1, 0, 0, 1, 0],
                [0, 0, 1, 0, 0, 1, 0, 0, 1]])

In [ ]:
lhs

array([[1, 1, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 1, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 1, 1],
       [1, 0, 0, 1, 0, 0, 1, 0, 0],
       [0, 1, 0, 0, 1, 0, 0, 1, 0],
       [0, 0, 1, 0, 0, 1, 0, 0, 1]])

In [ ]:
rhs = np.array([100, 300, 300, 300, 200, 200])

In [ ]:
rhs

array([100, 300, 300, 300, 200, 200])

In [ ]:
res = linprog(c=obj, A_eq=lhs, b_eq=rhs, bounds=(0,None), method="simplex")

<ipython-input-6-7786a95cf412>:1: DeprecationWarning: `method='simplex'` is deprecated and will be removed in SciPy 1.11.0. Please use one of the HiGHS solvers (e.g. `method='highs'`) in new code.
  res = linprog(c=obj, A_eq=lhs, b_eq=rhs, bounds=(0,None), method="simplex")
<ipython-input-6-7786a95cf412>:1: OptimizeWarning: A_eq does not appear to be of full row rank. To improve performance, check the problem formulation for redundant equality constraints.
  res = linprog(c=obj, A_eq=lhs, b_eq=rhs, bounds=(0,None), method="simplex")


In [ ]:
print(res)

 message: Optimization terminated successfully.
 success: True
  status: 0
     fun: 3000.0
       x: [ 0.000e+00  1.000e+02  0.000e+00  3.000e+02  0.000e+00
            0.000e+00  0.000e+00  1.000e+02  2.000e+02]
     nit: 9


In [ ]:
print('****************************')

print('\nOptimal value:', round(res.fun, ndigits=2))
print('\nOptimal variables: WE =', round(res.x[0], ndigits=2), 'WT =', round(res.x[1], ndigits=2), 'WO =', round(res.x[2], ndigits=2),'ME =', round(res.x[3], ndigits=2),'MT =', round(res.x[4], ndigits=2),'MO =', round(res.x[5], ndigits=2),'HE =', round(res.x[6], ndigits=2),'HT =', round(res.x[7], ndigits=2),'HO =', round(res.x[8], ndigits=2))
print('\nNumber of iterations performed:', res.nit)
print('\nStatus:', res.message)

****************************

Optimal value: 3000.0

Optimal variables: WE = 0.0 WT = 100.0 WO = 0.0 ME = 300.0 MT = 0.0 MO = 0.0 HE = 0.0 HT = 100.0 HO = 200.0

Number of iterations performed: 9

Status: Optimization terminated successfully.


<img src="https://github.com/amirkfard/CVL609-W23/blob/main/img/tranexamp.webp?raw=1\" width="700">

In [ ]:
import numpy as np
from scipy.optimize import linprog

# Define the coefficients for the objective function
#               1A  1B  1C  2A  2B  2C
obj = np.array([15, 35, 25, 10, 30, 40])

In [ ]:
#                1A 1B 1C 2A 2B 2C                
lhs = np.array([[1, 1, 1, 0, 0, 0],
                [0, 0, 0, 1, 1, 1],
                [1, 0, 0, 1, 0, 0],
                [0, 1, 0, 0, 1, 0],
                [0, 0, 1, 0, 0, 1]])

In [ ]:
rhs = np.array([40, 50, 30, 30, 30])

In [ ]:
res = linprog(c=obj, A_eq=lhs, b_eq=rhs, bounds=(0,20), method="simplex")

<ipython-input-20-b6215cd32a56>:1: DeprecationWarning: `method='simplex'` is deprecated and will be removed in SciPy 1.11.0. Please use one of the HiGHS solvers (e.g. `method='highs'`) in new code.
  res = linprog(c=obj, A_eq=lhs, b_eq=rhs, bounds=(0,20), method="simplex")
<ipython-input-20-b6215cd32a56>:1: OptimizeWarning: A_eq does not appear to be of full row rank. To improve performance, check the problem formulation for redundant equality constraints.
  res = linprog(c=obj, A_eq=lhs, b_eq=rhs, bounds=(0,20), method="simplex")


In [ ]:
res

 message: Optimization terminated successfully.
 success: True
  status: 0
     fun: 2200.0
       x: [ 1.000e+01  1.000e+01  2.000e+01  2.000e+01  2.000e+01
            1.000e+01]
     nit: 12

#Unbalanced Models





**Unbalanced Transportation Model**

<img src="https://github.com/amirkfard/CVL609-W23/blob/main/img/mip_85.webp?raw=1\" width="700">

<img src="https://github.com/amirkfard/CVL609-W23/blob/main/img/mip_85.webp?raw=1\" width="700">

#Unbalanced Example

<img src="https://github.com/amirkfard/CVL609-W23/blob/main/img/mip_86.webp?raw=1\" width="700">


In [ ]:
import numpy as np
from scipy.optimize import linprog

# Define the coefficients for the objective function
#               WE WT WO ME MT MO HE HT HO
obj = np.array([5, 4, 3, 3, 2, 1, 9, 7, 5])

In [ ]:
#                   WE WT WO ME MT MO HE HT HO               
lhs_ub = np.array([[1, 1, 1, 0, 0, 0, 0, 0 ,0],
                   [0, 0, 0, 1, 1, 1, 0, 0, 0],
                   [0, 0, 0, 0, 0, 0, 1, 1, 1]])

In [ ]:
lhs_ub

array([[1, 1, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 1, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 1, 1]])

In [ ]:
#                  WE WT WO ME MT MO HE HT HO               
lhs_eq = np.array([[1, 0, 0, 1, 0, 0, 1, 0, 0],
                   [0, 1, 0, 0, 1, 0, 0, 1, 0],
                   [0, 0, 1, 0, 0, 1, 0, 0, 1]])

In [ ]:
lhs_eq

array([[1, 0, 0, 1, 0, 0, 1, 0, 0],
       [0, 1, 0, 0, 1, 0, 0, 1, 0],
       [0, 0, 1, 0, 0, 1, 0, 0, 1]])

In [ ]:
rhs = np.array([300, 200, 200])

In [ ]:
rhs_ub = np.array([100, 300, 300])

In [ ]:
res = linprog(c= obj, A_ub=lhs_ub, A_eq=lhs_eq, b_ub=rhs_ub, b_eq=rhs, bounds=(0,None), method="simplex")

<ipython-input-47-13dce18afd50>:1: DeprecationWarning: `method='simplex'` is deprecated and will be removed in SciPy 1.11.0. Please use one of the HiGHS solvers (e.g. `method='highs'`) in new code.
  res = linprog(c= obj, A_ub=lhs_ub, A_eq=lhs_eq, b_ub=rhs_ub, b_eq=rhs, bounds=(0,None), method="simplex")


In [ ]:
res

 message: Optimization terminated successfully.
 success: True
  status: 0
     fun: 3000.0
       x: [ 1.000e+02  0.000e+00  0.000e+00  2.000e+02  1.000e+02
            0.000e+00  0.000e+00  1.000e+02  2.000e+02]
     nit: 12